# Generated by Django 4.1.4 on 2023-01-09 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Registered_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=40)),
                ('adder', models.TextField(max_length=500)),
                ('userid', models.CharField(max_length=20)),
                ('pwd1', models.CharField(max_length=60)),
                ('pwd2', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
