# Generated by Django 4.1.4 on 2023-01-10 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0003_customers_alter_registered_user_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='c_id',
            field=models.IntegerField(unique=True),
        ),
    ]
