# Generated by Django 4.1.4 on 2023-01-10 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0004_alter_customers_c_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_id', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=40)),
                ('adder', models.TextField(max_length=500)),
                ('gst', models.CharField(max_length=16, unique=True)),
                ('co_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('ord_name', models.CharField(max_length=60)),
                ('ord_number', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Customers',
        ),
    ]
