# Generated by Django 4.1.4 on 2023-01-10 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0005_customer_delete_customers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gst',
            field=models.CharField(max_length=16),
        ),
    ]
