# Generated by Django 4.1.4 on 2023-01-10 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0007_delete_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namei', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=40)),
                ('gst', models.CharField(max_length=50)),
                ('adder', models.TextField(max_length=500)),
                ('co_name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('ord_name', models.CharField(max_length=50)),
            ],
        ),
    ]
