# Generated by Django 4.1.4 on 2023-01-10 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0009_customer_date_alter_customer_gst_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_bill', models.IntegerField()),
                ('tot', models.IntegerField()),
                ('gst', models.CharField(max_length=5)),
                ('p_bill', models.IntegerField()),
                ('cleared', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='ord_amt',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='payed',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
