# Generated by Django 4.1.4 on 2023-01-10 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0011_alter_customer_ord_amt_alter_customer_payed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='ord_amt',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='payed',
        ),
    ]
