# Generated by Django 4.1.4 on 2023-01-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0012_remove_customer_ord_amt_remove_customer_payed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bills',
        ),
    ]
