# Generated by Django 4.1.4 on 2023-01-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0013_delete_bills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ord_bill', models.IntegerField()),
                ('tot', models.IntegerField()),
                ('gst', models.CharField(max_length=5)),
                ('p_bill', models.IntegerField()),
                ('cleared', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='ord_amt',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='payed',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
