# Generated by Django 4.1.4 on 2023-01-12 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0016_bills_co_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ssn', models.CharField(max_length=20)),
                ('E_name', models.CharField(max_length=50)),
                ('Salary', models.IntegerField(verbose_name=0)),
                ('E_address', models.TextField(max_length=500)),
                ('E_phone', models.CharField(max_length=13)),
                ('Gender', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=50)),
                ('Join_date', models.DateField()),
            ],
        ),
    ]
