# Generated by Django 4.1.4 on 2023-01-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0017_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='username',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
