# Generated by Django 4.1.4 on 2023-01-12 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0018_employees_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='password',
            field=models.CharField(default='0', max_length=60),
        ),
    ]
