# Generated by Django 4.1.4 on 2023-01-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0019_employees_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registered_user',
            name='pwd2',
        ),
    ]
