# Generated by Django 4.1.4 on 2023-01-14 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0020_remove_registered_user_pwd2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
