# Generated by Django 4.1.4 on 2023-01-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0021_alter_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bills',
            name='customer_id',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
