# Generated by Django 4.1.4 on 2023-01-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0022_bills_customer_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='id',
        ),
        migrations.AlterField(
            model_name='employees',
            name='Ssn',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
