# Generated by Django 4.1.4 on 2023-01-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0023_remove_employees_id_alter_employees_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Ssn',
            field=models.IntegerField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
