# Generated by Django 4.1.4 on 2023-01-15 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0024_alter_employees_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='Salary',
            field=models.IntegerField(),
        ),
    ]
