# Generated by Django 4.1.4 on 2023-01-15 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0026_alter_employees_ssn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bills',
            name='id',
        ),
        migrations.AddField(
            model_name='bills',
            name='ord_name',
            field=models.CharField(default='0', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='ord_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
