# Generated by Django 4.1.4 on 2023-01-16 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0027_remove_bills_id_bills_ord_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('Dnumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Dname', models.CharField(max_length=100)),
                ('D_manager', models.CharField(max_length=100)),
                ('mgr_ssn', models.IntegerField(unique=True)),
                ('Ssn', models.IntegerField()),
            ],
        ),
    ]
