# Generated by Django 4.1.4 on 2023-01-16 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0028_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='department',
            name='D_manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='Ssn',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='mgr_ssn',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
