# Generated by Django 4.1.4 on 2023-01-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0029_employees_manager_alter_department_d_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='D_manager',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='Ssn',
            field=models.IntegerField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='department',
            name='mgr_ssn',
            field=models.IntegerField(blank=True, default='None', unique=True),
        ),
    ]
