# Generated by Django 4.1.4 on 2023-01-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0030_alter_department_d_manager_alter_department_ssn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='Ssn',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='mgr_ssn',
            field=models.IntegerField(blank=True, default=0, unique=True),
        ),
    ]
