# Generated by Django 4.1.4 on 2023-01-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0031_alter_department_ssn_alter_department_mgr_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='D_manager',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='Ssn',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='mgr_ssn',
            field=models.IntegerField(blank=True, unique=True),
        ),
    ]
