# Generated by Django 4.1.4 on 2023-01-16 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0033_alter_department_d_manager_alter_department_ssn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='D_manager',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='Ssn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='mgr_ssn',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
