# Generated by Django 4.1.4 on 2023-01-16 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_vs', '0034_alter_department_d_manager_alter_department_ssn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='manager',
        ),
    ]
